# Generated by Django 4.1.4 on 2023-09-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit'), ('deposit', 'deposit'), ('withdraw', 'withdraw')], default='true', max_length=10),
        ),
    ]
