# Generated by Django 4.1.4 on 2023-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit'), ('deposit', 'deposit'), ('withdraw', 'withdraw')], default='credit', max_length=10),
        ),
    ]
