# Generated by Django 4.1.4 on 2023-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_transaction_options_customer_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recv_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
